# Test Your Understanding of Tensor Dimensions

Work through each section, predict the output **before** running the cell, then verify.

Fill in code where you see `...` or `#TODO`.

In [2]:
import torch

---
## Part 1: Shape and Rank

Predict the `shape`, `ndim`, and `numel()` of each tensor before running.

In [3]:
a = torch.tensor(7)
b = torch.tensor([1, 2, 3, 4])
c = torch.tensor([[1, 2], [3, 4], [5, 6]])
d = torch.randn(2, 3, 4)

# TODO: Before running, write down what you expect for each
#   a.shape = ?    a.ndim = ?    a.numel() = ?
#   b.shape = ?    b.ndim = ?    b.numel() = ?
#   c.shape = ?    c.ndim = ?    c.numel() = ?
#   d.shape = ?    d.ndim = ?    d.numel() = ?

for name, t in [('a', a), ('b', b), ('c', c), ('d', d)]:
    print(f"{name}: shape={t.shape}, ndim={t.ndim}, numel={t.numel()}")

a: shape=torch.Size([]), ndim=0, numel=1
b: shape=torch.Size([4]), ndim=1, numel=4
c: shape=torch.Size([3, 2]), ndim=2, numel=6
d: shape=torch.Size([2, 3, 4]), ndim=3, numel=24


---
## Part 2: Understanding `dim` in Reductions

Given a matrix, predict what `sum(dim=0)` and `sum(dim=1)` produce.

In [4]:
x = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("x:")
print(x)
print(f"x.shape = {x.shape}")
print()

# TODO: Predict the result and shape before running
# shape (3,3)
print("sum(dim=0):", x.sum(dim=0), x.sum(dim=0).shape )   # result shape? [3]
print("sum(dim=1):", x.sum(dim=1), x.sum(dim=1).shape )   # result shape? [3]
print("sum(dim=-1):", x.sum(dim=-1), x.sum(dim=-1).shape) # same as which dim? [3]

x:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x.shape = torch.Size([3, 3])

sum(dim=0): tensor([12, 15, 18]) torch.Size([3])
sum(dim=1): tensor([ 6, 15, 24]) torch.Size([3])
sum(dim=-1): tensor([ 6, 15, 24]) torch.Size([3])


### Exercise 2a: 3-D Reductions

This is where it gets interesting. Think carefully about which axis is collapsed.

In [5]:
x = torch.arange(24).reshape(2, 3, 4)
print("x.shape =", x.shape)
print(x)
print()

x.shape = torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])



In [6]:
x = torch.arange(24).reshape(2, 3, 4)
print("x.shape =", x.shape)
print(x)
print()

# TODO: Predict each result shape before running
s0 = x.sum(dim=0)
s1 = x.sum(dim=1)
s2 = x.sum(dim=2)

print(f"sum(dim=0): shape={s0.shape}") # (3,4)
print(s0)
print()
print(f"sum(dim=1): shape={s1.shape}") # (2,4)
print(s1)
print()
print(f"sum(dim=2): shape={s2.shape}") # (2,3)
print(s2)

x.shape = torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

sum(dim=0): shape=torch.Size([3, 4])
tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

sum(dim=1): shape=torch.Size([2, 4])
tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

sum(dim=2): shape=torch.Size([2, 3])
tensor([[ 6, 22, 38],
        [54, 70, 86]])


### Exercise 2b: Your Turn

Use reductions to answer the following questions about the tensor below.

In [12]:
# Imagine this is a batch of 4 grayscale images, each 3x3 pixels
images = torch.tensor([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],       # image 0
    [[9, 8, 7], [6, 5, 4], [3, 2, 1]],       # image 1
    [[1, 1, 1], [1, 1, 1], [1, 1, 1]],       # image 2
    [[0, 0, 0], [0, 9, 0], [0, 0, 0]],       # image 3
], dtype=torch.float)

print("images.shape =", images.shape)  # (4, 3, 3)

# TODO: Compute the mean pixel value of EACH image (result should be shape (4,))
mean_per_image = images.mean(dim=(1,2))  # Hint: you need to reduce over two dims
print("Mean per image:", mean_per_image)

# TODO: Compute the pixel-wise max across all images (result should be shape (3, 3))
max_across_batch = images.max(dim=0)  # Hint: which dim is the batch dim?
print("Max across batch:\n", max_across_batch)

images.shape = torch.Size([4, 3, 3])
Mean per image: tensor([5., 5., 1., 1.])
Max across batch:
 torch.return_types.max(
values=tensor([[9., 8., 7.],
        [6., 9., 6.],
        [7., 8., 9.]]),
indices=tensor([[1, 1, 1],
        [1, 3, 0],
        [0, 0, 0]]))


---
## Part 3: `keepdim` and Broadcasting

Understand why `keepdim=True` matters for subsequent operations.

In [21]:
x = torch.tensor([[1.0, 2.0, 3.0],
                   [4.0, 5.0, 6.0]])

# Without keepdim
row_sum = x.sum(dim=1)
print (row_sum)
print(f"row_sum shape (no keepdim): {row_sum.shape}")  # predict this

# With keepdim
row_sum_kd = x.sum(dim=1, keepdim=True)
print (row_sum_kd)
print(f"row_sum shape (keepdim):    {row_sum_kd.shape}")  # predict this

# TODO: Which one can you use to normalize each row? Try both and see which errors.
# normalized = x / row_sum       # does this work?
normalized = x / row_sum_kd    # does this work?
print()

tensor([ 6., 15.])
row_sum shape (no keepdim): torch.Size([2])
tensor([[ 6.],
        [15.]])
row_sum shape (keepdim):    torch.Size([2, 1])



### Exercise 3a: Manual Softmax

Implement softmax yourself using `exp`, `sum`, and `keepdim`.

In [25]:
logits = torch.tensor([[2.0, 1.0, 0.1],
                        [0.5, 2.5, 1.0]])

# TODO: Implement softmax along dim=1 (each row should sum to 1)
# softmax(x_i) = exp(x_i) / sum(exp(x_j)) for all j in the row
my_softmax = torch.exp(logits)/torch.exp(logits).sum(dim=1,keepdim=True)  # your implementation here

# Verify against PyTorch's built-in
expected = torch.softmax(logits, dim=1)
print("Your softmax:\n", my_softmax)
print("Expected:\n", expected)
print("Match:", torch.allclose(my_softmax, expected))

Your softmax:
 tensor([[0.6590, 0.2424, 0.0986],
        [0.0996, 0.7361, 0.1643]])
Expected:
 tensor([[0.6590, 0.2424, 0.0986],
        [0.0996, 0.7361, 0.1643]])
Match: True


---
## Part 4: Squeeze and Unsqueeze

Practice adding and removing dimensions.

In [31]:
v = torch.tensor([10, 20, 30])  # shape: (3,)

# TODO: Predict each shape before running
print("unsqueeze(0):", v.unsqueeze(0).shape)   # ?
print (v.unsqueeze(0)) 
print("unsqueeze(1):", v.unsqueeze(1).shape)   # ?
print (v.unsqueeze(1)) 
print("unsqueeze(-1):", v.unsqueeze(-1).shape) # ?
print (v.unsqueeze(-1)) 
print("[None, :]:", v[None, :].shape)          # ?
print("[:, None]:", v[:, None].shape)           # ?

unsqueeze(0): torch.Size([1, 3])
tensor([[10, 20, 30]])
unsqueeze(1): torch.Size([3, 1])
tensor([[10],
        [20],
        [30]])
unsqueeze(-1): torch.Size([3, 1])
tensor([[10],
        [20],
        [30]])
[None, :]: torch.Size([1, 3])
[:, None]: torch.Size([3, 1])


In [32]:
x = torch.randn(1, 3, 1, 5, 1)

# TODO: Predict each shape before running
print("original:", x.shape)
print("squeeze():", x.squeeze().shape)     # removes ALL size-1 dims
print (x.squeeze()) 
print("squeeze(0):", x.squeeze(0).shape)   # removes only dim 0 if size 1
print (x.squeeze(0)) 
print("squeeze(1):", x.squeeze(1).shape)   # dim 1 is size 3, so...?
print (x.squeeze(1)) 
print("squeeze(2):", x.squeeze(2).shape)   # removes only dim 2 if size 1
print (x.squeeze(2)) 

original: torch.Size([1, 3, 1, 5, 1])
squeeze(): torch.Size([3, 5])
tensor([[-0.1776, -0.4358, -0.0340,  1.7463, -1.4872],
        [ 0.6886,  0.9414, -0.8473,  0.6787, -0.8645],
        [-0.7937, -0.4214, -1.4925, -0.6108, -1.1461]])
squeeze(0): torch.Size([3, 1, 5, 1])
tensor([[[[-0.1776],
          [-0.4358],
          [-0.0340],
          [ 1.7463],
          [-1.4872]]],


        [[[ 0.6886],
          [ 0.9414],
          [-0.8473],
          [ 0.6787],
          [-0.8645]]],


        [[[-0.7937],
          [-0.4214],
          [-1.4925],
          [-0.6108],
          [-1.1461]]]])
squeeze(1): torch.Size([1, 3, 1, 5, 1])
tensor([[[[[-0.1776],
           [-0.4358],
           [-0.0340],
           [ 1.7463],
           [-1.4872]]],


         [[[ 0.6886],
           [ 0.9414],
           [-0.8473],
           [ 0.6787],
           [-0.8645]]],


         [[[-0.7937],
           [-0.4214],
           [-1.4925],
           [-0.6108],
           [-1.1461]]]]])
squeeze(2): torch.Siz

### Exercise 4a: Fix the Shape

A common scenario: you have a single image and need to add a batch dimension for a model.

In [33]:
single_image = torch.randn(3, 32, 32)  # shape: (C, H, W)

# A model expects (B, C, H, W). Add a batch dimension of size 1.
# TODO: use unsqueeze to create batched_image with shape (1, 3, 32, 32)
batched_image = single_image.unsqueeze(0)
print("batched_image.shape =", batched_image.shape)
assert batched_image.shape == torch.Size([1, 3, 32, 32])

# Now suppose the model returns output with shape (1, 10). Remove the batch dim.
model_output = torch.randn(1, 10)
# TODO: use squeeze to get shape (10,)
prediction = model_output.squeeze(0)
print("prediction.shape =", prediction.shape)
assert prediction.shape == torch.Size([10])

batched_image.shape = torch.Size([1, 3, 32, 32])
prediction.shape = torch.Size([10])


---
## Part 5: Reshape, View, Flatten

Practice reorganizing tensor data.

In [36]:
help(x.reshape)

Help on built-in function reshape:

reshape(...) method of torch.Tensor instance
    reshape(*shape) -> Tensor

    Returns a tensor with the same data and number of elements as :attr:`self`
    but with the specified shape. This method returns a view if :attr:`shape` is
    compatible with the current shape. See :meth:`torch.Tensor.view` on when it is
    possible to return a view.

    See :func:`torch.reshape`

    Args:
        shape (tuple of ints or int...): the desired shape



In [35]:
x = torch.arange(24)
print("x.shape =", x.shape)  # (24,)

# TODO: Reshape x into each of the following shapes using reshape or view
a = x.reshape(6,4)
b = x.reshape(2,3,4)
c = x.reshape(4,-1)  # shape: (4, -1)  — let PyTorch figure out the last dim

print(f"a.shape = {a.shape}")  # should be (6, 4)
print(f"b.shape = {b.shape}")  # should be (2, 3, 4)
print(f"c.shape = {c.shape}")  # should be (4, 6)

x.shape = torch.Size([24])
a.shape = torch.Size([6, 4])
b.shape = torch.Size([2, 3, 4])
c.shape = torch.Size([4, 6])


In [39]:
help(x.flatten)

Help on built-in function flatten:

flatten(...) method of torch.Tensor instance
    flatten(start_dim=0, end_dim=-1) -> Tensor

    See :func:`torch.flatten`



In [46]:
# Flatten exercise
images = torch.randn(16, 3, 28, 28)  # batch of 16 RGB images, 28x28

# TODO: Flatten each image to a 1-D vector, keeping the batch dim
# Result shape should be (16, 2352) where 2352 = 3*28*28
flat = images.flatten(start_dim=1)
print(f"flat.shape = {flat.shape}")
assert flat.shape == torch.Size([16, 2352])

# TODO: Flatten only the spatial dims (H, W), keeping batch and channel
# Result shape should be (16, 3, 784) where 784 = 28*28
spatial_flat = images.flatten(start_dim=2)
print(f"spatial_flat.shape = {spatial_flat.shape}")
assert spatial_flat.shape == torch.Size([16, 3, 784])

flat.shape = torch.Size([16, 2352])
spatial_flat.shape = torch.Size([16, 3, 784])


---
## Part 6: Transpose and Permute

In [52]:
x = torch.randn(2, 3, 4)
print (x)

# TODO: Predict each shape before running
print("transpose(0,1):", x.transpose(0, 1).shape)   # 3,2,4
print (x.transpose(1, 2))
print("transpose(1,2):", x.transpose(1, 2).shape)   # 2,4,3
print("permute(2,0,1):", x.permute(2, 0, 1).shape)  # 4,2,3

tensor([[[ 0.7548, -0.0720, -0.1672, -0.5136],
         [-0.2793,  0.7769, -0.7162, -0.4065],
         [-0.1436,  1.1106, -1.0773,  2.3336]],

        [[ 0.9293, -0.8232, -0.6673,  0.1459],
         [ 1.1378, -0.3859,  0.1117, -0.4174],
         [ 0.2757, -0.2401, -0.6615,  0.4611]]])
transpose(0,1): torch.Size([3, 2, 4])
tensor([[[ 0.7548, -0.2793, -0.1436],
         [-0.0720,  0.7769,  1.1106],
         [-0.1672, -0.7162, -1.0773],
         [-0.5136, -0.4065,  2.3336]],

        [[ 0.9293,  1.1378,  0.2757],
         [-0.8232, -0.3859, -0.2401],
         [-0.6673,  0.1117, -0.6615],
         [ 0.1459, -0.4174,  0.4611]]])
transpose(1,2): torch.Size([2, 4, 3])
permute(2,0,1): torch.Size([4, 2, 3])


### Exercise 6a: Channel Conversion

A common real-world task: convert between channel-last (NHWC) and channel-first (NCHW) formats.

In [55]:
# Simulating images loaded by a library that uses channel-last (NHWC)
images_nhwc = torch.randn(8, 32, 32, 3)  # (N, H, W, C)

# NHWC → NCHW: move dim 3 (C) to position 1
images_nchw = images_nhwc.permute(0, 3, 1, 2)
print(f"images_nchw.shape = {images_nchw.shape}")  # (8, 3, 32, 32)
assert images_nchw.shape == torch.Size([8, 3, 32, 32])

# NCHW → NHWC: move dim 1 (C) to position 3
images_back = images_nchw.permute(0, 2, 3, 1)
print(f"images_back.shape = {images_back.shape}")  # (8, 32, 32, 3)
assert images_back.shape == torch.Size([8, 32, 32, 3])

images_nchw.shape = torch.Size([8, 3, 32, 32])
images_back.shape = torch.Size([8, 32, 32, 3])


---
## Part 7: Cat, Stack, Unbind

Combining and splitting tensors.

In [60]:
a = torch.ones(2, 3)
b = torch.zeros(2, 3)

# TODO: Predict each shape before running
print("cat dim=0:", torch.cat([a, b], dim=0).shape)     # ?
print (torch.cat([a, b], dim=0))
print("cat dim=1:", torch.cat([a, b], dim=1).shape)     # ?
print (torch.cat([a, b], dim=1))
print("stack dim=0:", torch.stack([a, b], dim=0).shape) # ?
print (torch.stack([a, b], dim=0))
print("stack dim=1:", torch.stack([a, b], dim=1).shape) # ?
print (torch.stack([a, b], dim=1))

cat dim=0: torch.Size([4, 3])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])
cat dim=1: torch.Size([2, 6])
tensor([[1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.]])
stack dim=0: torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
stack dim=1: torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [0., 0., 0.]]])


### Exercise 7a: Build a Batch

You have individual samples and need to combine them into a batch.

In [62]:
# 5 individual images, each (3, 16, 16)
samples = [torch.randn(3, 16, 16) for _ in range(5)]

# TODO: Combine into a single batch tensor of shape (5, 3, 16, 16)
batch = torch.stack(samples, dim=0)
print(f"batch.shape = {batch.shape}")
assert batch.shape == torch.Size([5, 3, 16, 16])

# TODO: Split the batch back into a list of 5 individual images
# Each should be shape (3, 16, 16)
individuals = torch.unbind(batch, dim=0)
print(f"Number of images: {len(individuals)}")
print(f"Each image shape: {individuals[0].shape}")
assert len(individuals) == 5
assert individuals[0].shape == torch.Size([3, 16, 16])

batch.shape = torch.Size([5, 3, 16, 16])
Number of images: 5
Each image shape: torch.Size([3, 16, 16])


---
## Part 8: Gather and Scatter

These are trickier — used heavily in embedding lookups and loss computation.

In [ ]:
# Suppose these are model logits for 4 samples, 5 classes each
logits = torch.tensor([[0.1, 0.9, 0.2, 0.3, 0.5],
                        [0.8, 0.1, 0.3, 0.6, 0.2],
                        [0.2, 0.3, 0.7, 0.1, 0.4],
                        [0.1, 0.2, 0.1, 0.9, 0.3]])

# True labels for each sample
labels = torch.tensor([1, 0, 2, 3])

# TODO: Use torch.gather to extract the logit at the correct class for each sample
# Hint: gather needs a 2-D index tensor with shape matching the output
# Expected result: tensor([0.9, 0.8, 0.7, 0.9])
correct_logits = ...
print("Logits at correct classes:", correct_logits)

In [ ]:
# One-hot encoding using scatter
labels = torch.tensor([0, 2, 1, 4, 3])
num_classes = 5

# TODO: Create a one-hot matrix of shape (5, 5) using scatter_
# Each row should have a 1 at the index specified by the label
# Hint: start with zeros, then scatter ones into the right positions
one_hot = ...
print("One-hot:\n", one_hot)
# Expected:
# tensor([[1, 0, 0, 0, 0],
#         [0, 0, 1, 0, 0],
#         [0, 1, 0, 0, 0],
#         [0, 0, 0, 0, 1],
#         [0, 0, 0, 1, 0]])

---
## Part 9: Expand and Repeat

In [ ]:
x = torch.tensor([[1], [2], [3]])  # shape: (3, 1)

# TODO: Predict shapes and values before running
print("expand(3,4):\n", x.expand(3, 4))       # shape?
print("expand(-1,4):\n", x.expand(-1, 4))     # shape?
print()

y = torch.tensor([1, 2, 3])  # shape: (3,)
print("repeat(3):", y.repeat(3))           # shape & values?
print("repeat(2,3):\n", y.repeat(2, 3))    # shape & values?

### Exercise 9a: Broadcasting vs Expand

Show that you don't always need `expand` — broadcasting handles it automatically.

In [ ]:
# Subtract the row-mean from each element (center each row)
data = torch.tensor([[10.0, 20.0, 30.0],
                      [40.0, 50.0, 60.0]])

# Method 1: explicit expand (verbose)
row_means = data.mean(dim=1, keepdim=True)  # shape: (2, 1)
centered_v1 = data - row_means.expand(-1, 3)  # manually expand to (2, 3)

# TODO Method 2: just use broadcasting (simpler)
centered_v2 = ...  # same result, no expand needed

print("Centered (expand):\n", centered_v1)
print("Centered (broadcast):\n", centered_v2)
print("Same result:", torch.allclose(centered_v1, centered_v2))

---
## Part 10: Flip, Roll, and Narrow

In [ ]:
x = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# TODO: Predict each result before running
print("flip dims=[0]:\n", torch.flip(x, dims=[0]))
print("flip dims=[1]:\n", torch.flip(x, dims=[1]))
print("flip dims=[0,1]:\n", torch.flip(x, dims=[0, 1]))

In [ ]:
x = torch.tensor([1, 2, 3, 4, 5])

# TODO: Predict each result before running
print("roll 2:", torch.roll(x, shifts=2))
print("roll -1:", torch.roll(x, shifts=-1))

### Exercise 10a: Crop an Image

Use `narrow` to extract a region from an image tensor.

In [ ]:
image = torch.arange(48).reshape(3, 4, 4)  # (C=3, H=4, W=4)
print("Full image shape:", image.shape)
print("Channel 0:\n", image[0])

# TODO: Extract a 2x2 crop from the top-left corner (all channels)
# Result shape should be (3, 2, 2)
# Hint: use narrow twice — once on H, once on W
crop = ...
print(f"\ncrop.shape = {crop.shape}")
print("Channel 0 of crop:\n", crop[0])
assert crop.shape == torch.Size([3, 2, 2])

---
## Part 11: Contiguity

Understand when `view` fails and why `reshape` is safer.

In [ ]:
x = torch.arange(12).reshape(3, 4)
print("x is contiguous:", x.is_contiguous())

y = x.transpose(0, 1)  # (4, 3)
print("y is contiguous:", y.is_contiguous())

# TODO: Try y.view(12) — what happens?
# Then fix it two different ways:
#   1. Using .contiguous().view()
#   2. Using .reshape()

# Uncomment and test:
# flat_fail = y.view(12)               # this will error
# flat_fix1 = y.contiguous().view(12)   # fix 1
# flat_fix2 = y.reshape(12)             # fix 2
# print(flat_fix1)
# print(flat_fix2)

---
## Part 12: Putting It All Together

A mini challenge that combines multiple concepts.

In [65]:
# You receive attention scores from a multi-head attention layer.
# Shape: (batch, num_heads, seq_len, seq_len)
batch_size, num_heads, seq_len = 2, 4, 8
attn_scores = torch.randn(batch_size, num_heads, seq_len, seq_len)
print(f"Input: {attn_scores.shape}")  # (2, 4, 8, 8)

# TODO Step 1: Compute softmax over the last dimension (each row of the attention matrix)
attn_probs = torch.softmax(attn_scores, dim=-1)
print(f"After softmax: {attn_probs.shape}")  # should still be (2, 4, 8, 8)

# Verify: each row should sum to 1
row_sums = attn_probs.sum(dim=-1)
print(f"Row sums (should all be ~1.0): min={row_sums.min():.4f}, max={row_sums.max():.4f}")

# TODO Step 2: Average the attention weights across all heads
# Result shape: (2, 8, 8) — one attention map per batch item
avg_attn = attn_probs.mean(dim=1)
print(f"Averaged over heads: {avg_attn.shape}")  # (2, 8, 8)
assert avg_attn.shape == torch.Size([2, 8, 8])

# TODO Step 3: Flatten the 8x8 attention maps into vectors
# Result shape: (2, 64)
flat_attn = avg_attn.flatten(start_dim=1)
print(f"Flattened: {flat_attn.shape}")  # (2, 64)
assert flat_attn.shape == torch.Size([2, 64])

# TODO Step 4: Find which position each query attends to most (argmax) in avg_attn
# Result shape: (2, 8) — for each batch & query position, the most-attended key
most_attended = avg_attn.argmax(dim=-1)
print(f"Most attended positions: {most_attended.shape}")  # (2, 8)
print(most_attended)
assert most_attended.shape == torch.Size([2, 8])

Input: torch.Size([2, 4, 8, 8])
After softmax: torch.Size([2, 4, 8, 8])
Row sums (should all be ~1.0): min=1.0000, max=1.0000
Averaged over heads: torch.Size([2, 8, 8])
Flattened: torch.Size([2, 64])
Most attended positions: torch.Size([2, 8])
tensor([[6, 6, 6, 1, 5, 5, 3, 3],
        [6, 1, 3, 6, 1, 6, 2, 4]])


In [66]:
print("All done! If you got here without errors, you understand tensor dimensions well.")

All done! If you got here without errors, you understand tensor dimensions well.
